from __future__ import annotations

import argparse
import logging
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from preprocess.config import load_config, resolve_path
from preprocess.io_utils import ensure_dir, iter_json_records
from preprocess.logging_utils import setup_logging
from preprocess.paths import bootstrap_layout, link_or_copy_raw_layout
from preprocess.schema_utils import FileSchemaSummary

logger = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Inspect raw JSONL/JSON.GZ schemas.")
    parser.add_argument("--config", required=True, help="Path to configs/preprocess.yaml")
    parser.add_argument("--sample-lines", type=int, default=None, help="Lines per file to inspect")
    parser.add_argument("--limit-files", type=int, default=None, help="Limit number of files scanned")
    parser.add_argument("--start-date", help="Inclusive date filter in YYYYMMDD")
    parser.add_argument("--end-date", help="Inclusive date filter in YYYYMMDD")
    parser.add_argument("--source", choices=["binance", "polymarket"], help="Restrict to one source")
    parser.add_argument("--dry-run", action="store_true", help="Do not create data/raw links")
    return parser.parse_args()


def discover_raw_files(
    config: dict,
    limit_files: int | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
    source: str | None = None,
) -> list[Path]:
    files: list[Path] = []
    for key in ("binance", "polymarket"):
        if source and key != source:
            continue
        root = resolve_path(config, config["raw_paths"][key])
        if not root.exists():
            continue
        files.extend(sorted(root.rglob("*.jsonl.gz")))
        files.extend(sorted(root.rglob("*.json.gz")))
        files.extend(sorted(root.rglob("*.jsonl")))
    files = sorted(set(files))
    if start_date or end_date:
        filtered = []
        for path in files:
            date_part = next((part for part in path.parts if len(part) == 8 and part.isdigit()), None)
            if date_part is None:
                continue
            if start_date and date_part < start_date:
                continue
            if end_date and date_part > end_date:
                continue
            filtered.append(path)
        files = filtered
    if limit_files is not None:
        files = files[:limit_files]
    return files


def write_report(config: dict, summaries: list[FileSchemaSummary]) -> Path:
    reports_dir = resolve_path(config, config["output_paths"]["reports"])
    ensure_dir(reports_dir)
    report_path = reports_dir / "raw_schema_report.md"
    lines: list[str] = []
    lines.append("# Raw Schema Report")
    lines.append("")
    lines.append("This report is generated by `scripts/inspect_raw.py`.")
    lines.append("")
    lines.append("## Mapping Notes")
    lines.append("")
    lines.append("- Update `configs/preprocess.yaml` under `schema_mapping` if raw field names change.")
    lines.append("- Outcome mapping for Polymarket may require manual enrichment when YES/NO is not explicit.")
    lines.append("- `recv_ns` is currently used as the main receive timestamp candidate for both sources.")
    lines.append("")
    for summary in summaries:
        lines.append(f"## `{summary.path}`")
        lines.append("")
        lines.append("### Record Type Counts")
        lines.append("")
        for key, count in sorted(summary.record_types.items()):
            lines.append(f"- `{key}`: {count}")
        lines.append("")
        lines.append("### Top Level Keys")
        lines.append("")
        for key in sorted(summary.top_level_keys):
            lines.append(f"- `{key}`")
        lines.append("")
        lines.append("### Nested Keys")
        lines.append("")
        for key in sorted(summary.nested_keys):
            samples = summary.sample_values.get(key, [])
            sample_text = f" samples={samples}" if samples else ""
            lines.append(f"- `{key}`{sample_text}")
        lines.append("")
        lines.append("### Timestamp Candidates")
        lines.append("")
        for key in sorted(summary.timestamp_candidates):
            lines.append(f"- `{key}`")
        lines.append("")
        lines.append("### ID Candidates")
        lines.append("")
        for key in sorted(summary.id_candidates):
            lines.append(f"- `{key}`")
        lines.append("")
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


def main() -> None:
    args = parse_args()
    setup_logging()
    config = load_config(args.config)
    bootstrap_layout(config)
    operations = link_or_copy_raw_layout(config, dry_run=args.dry_run)
    logger.info("Prepared %d raw file links under data/raw", len(operations))

    sample_lines = args.sample_lines or config.get("inspect", {}).get("sample_lines", 20)
    summaries: list[FileSchemaSummary] = []
    for path in discover_raw_files(
        config,
        limit_files=args.limit_files,
        start_date=args.start_date,
        end_date=args.end_date,
        source=args.source,
    ):
        logger.info("Inspecting %s", path)
        summary = FileSchemaSummary(path=str(path))
        for idx, record in enumerate(iter_json_records(path)):
            summary.add_record(record)
            if idx + 1 >= sample_lines:
                break
        summaries.append(summary)

    report_path = write_report(config, summaries)
    logger.info("Wrote raw schema report to %s", report_path)


if __name__ == "__main__":
    main()
